-- TPC/Monoid.lean  [github.com/FruitfulApproach/Lean4TPC/blob/main/TPC/Monoid.lean]
-- Product monoid M = (ℤ², ⊗), generating set G, submonoid N = ⟨G⟩,
-- and the topological monoid structure.

import TPC.Basic
import Mathlib.Topology.Basic
import Mathlib.Topology.Algebra.Monoid
import Mathlib.Tactic

namespace TPC

-- ── §1: Product monoid M = (ℤ², ⊗) ────────────────────────

def otimes (p q : ℤ × ℤ) : ℤ × ℤ :=
  (mstar p.1 q.1, sstar p.2 q.2)

notation:70 p " ⊗ " q => otimes p q

@[simp] lemma otimes_fst (a b c d : ℤ) : ((a,b) ⊗ (c,d)).1 = a ⊛ c := rfl
@[simp] lemma otimes_snd (a b c d : ℤ) : ((a,b) ⊗ (c,d)).2 = b ⋆ d := rfl

@[simp] lemma otimes_one_left  (p : ℤ × ℤ) : (0,0) ⊗ p = p := by
  simp [otimes, mstar, sstar]
@[simp] lemma otimes_one_right (p : ℤ × ℤ) : p ⊗ (0,0) = p := by
  simp [otimes, mstar, sstar]

lemma otimes_assoc (p q r : ℤ × ℤ) : (p ⊗ q) ⊗ r = p ⊗ (q ⊗ r) := by
  simp [otimes, mstar_assoc, sstar_assoc]

lemma otimes_comm (p q : ℤ × ℤ) : p ⊗ q = q ⊗ p := by
  simp [otimes, mstar_comm, sstar_comm]

instance : CommMonoid (ℤ × ℤ) where
  mul       := otimes
  mul_assoc := otimes_assoc
  one       := (0, 0)
  one_mul   := otimes_one_left
  mul_one   := otimes_one_right
  mul_comm  := otimes_comm

-- ── §2: Generating set G and submonoid N ───────────────────

/-- G = {(k,k) : k ∈ ℤ} is the usual diagonal -/
def G : Set (ℤ × ℤ) := {p | p.1 = p.2}

@[simp] lemma mem_G (k : ℤ) : (k, k) ∈ G := rfl

/-- The embedding Δ : ℤ → G -/
def Δ (k : ℤ) : ℤ × ℤ := (k, k)

@[simp] lemma Δ_mem (k : ℤ) : Δ k ∈ G := rfl

/-- N = ⟨G⟩ as a Submonoid -/
def N : Submonoid (ℤ × ℤ) := Submonoid.closure G

lemma Δ_mem_N (k : ℤ) : Δ k ∈ N :=
  Submonoid.subset_closure (Δ_mem k)

-- Elements of N have form (k₁ ⊛ ⋯ ⊛ kᵣ, k₁ ⋆ ⋯ ⋆ kᵣ)
-- for the SAME sequence k₁,...,kᵣ.
-- Note: (z,w) ∈ N does NOT imply z = w.
example : (8, -4) ∈ N := by
  have h := Submonoid.mul_mem N (Δ_mem_N 1) (Δ_mem_N 1)
  simp [Δ, otimes, mstar, sstar] at h
  convert h using 1 <;> norm_num [mstar, sstar]

-- ── §3: M is a topological monoid ─────────────────────────

-- Furstenberg topology on ℤ: generated by arithmetic progressions a + bℤ
-- Product topology on ℤ²

instance : TopologicalSpace ℤ :=
  TopologicalSpace.generateFrom {S | ∃ a b : ℤ, b ≠ 0 ∧ S = {x | ∃ z : ℤ, x = a + b * z}}

/-- mstar is continuous in the Furstenberg topology -/
lemma mstar_continuous : Continuous (fun p : ℤ × ℤ => p.1 ⊛ p.2) := by
  apply continuous_generateFrom_iff.mpr
  rintro S ⟨a, b, hb, rfl⟩
  -- preimage of a + bℤ under (x,y) ↦ 6xy+x+y
  -- neighbourhood (x₀ + bℤ) × (y₀ + bℤ) works: correction ≡ 0 mod b
  sorry

/-- sstar is continuous -/
lemma sstar_continuous : Continuous (fun p : ℤ × ℤ => p.1 ⋆ p.2) := by
  sorry -- identical argument to mstar_continuous

/-- ⊗ is continuous: M is a topological monoid -/
theorem otimes_continuous : Continuous (fun p : (ℤ×ℤ) × (ℤ×ℤ) => p.1 ⊗ p.2) := by
  apply Continuous.prod_mk
  · exact mstar_continuous.comp (continuous_fst.prod_mk (continuous_snd.comp continuous_fst))
  · exact sstar_continuous.comp
      ((continuous_snd.comp continuous_fst).prod_mk continuous_snd)

end TPC
