-- TPC/Main.lean
-- Main equivalence: TPC ⟺ {(0,0)} not open in (N, τ_N)
-- General Furstenberg criterion for generated monoids.

import TPC.Basic
import TPC.Monoid
import TPC.Diagonal
import TPC.Topology
import Mathlib.Tactic
import Mathlib.Data.Set.Finite

namespace TPC

-- ============================================================
-- Section 1: General Furstenberg Criterion
-- ============================================================

/-- General Furstenberg Criterion for generated monoids.

    Let (N, ·, e) be a commutative monoid generated by a set Irr.
    Equip N with the coarsest topology making every translate a·N closed.
    Then:
      |Irr| = ∞  ⟺  {e} is not open

    Direction (⇐): Irr finite → N\{e} = ⋃_{q∈Irr} q·N = finite union
                    of closed sets = closed → {e} open.
    Direction (⇒): Any finite covering N\{e} = ⋃ aᵢ·N forces every
                    irreducible to be one of the aᵢ → |Irr| ≤ k.

    The irreducibility argument for (⇒) requires:
    - No element a·r = q (irreducible) with both a,r nontrivial
    - This follows from a "norm" (like φ) mapping to a UFD where
      irreducibles map to primes. -/

-- We state this as a logical equivalence for our specific monoid.

-- ============================================================
-- Section 2: (⇐) direction — G finite implies {e} open
-- ============================================================

/-- If G is finite, then {(0,0)} is open in (N, τ_N) -/
theorem G_finite_implies_identity_open (hfin : G.Finite) :
    IsOpen ({(0, 0)} : Set (ℤ × ℤ)) := by
  -- N \ {(0,0)} = ⋃_{g ∈ G} translateN g (by H1)
  -- This is a finite union of closed sets, hence closed.
  -- So {(0,0)} is open.
  sorry

-- ============================================================
-- Section 3: (⇒) direction — G infinite implies {e} not open
-- ============================================================

/-- If G is infinite, then {(0,0)} is not open in (N, τ_N) -/
theorem G_infinite_implies_identity_not_open (hinf : G.Infinite) :
    ¬ IsOpen ({(0, 0)} : Set (ℤ × ℤ)) := by
  -- If {(0,0)} were open, then N \ {(0,0)} would be closed,
  -- hence a finite union of translates aᵢ ⊗ N.
  -- By generator_in_translate_forces_eq, every g ∈ G is one of the aᵢ.
  -- So |G| ≤ k, contradicting G.Infinite.
  sorry

-- ============================================================
-- Section 4: The equivalence
-- ============================================================

/-- TPC ⟺ {(0,0)} not open:
    |G| = ∞  ⟺  {(0,0)} is not open in (N, τ_N) -/
theorem TPC_equivalence :
    G.Infinite ↔ ¬ IsOpen ({(0, 0)} : Set (ℤ × ℤ)) := by
  constructor
  · exact G_infinite_implies_identity_not_open
  · intro h
    by_contra hfin
    rw [Set.not_infinite] at hfin
    exact h (G_finite_implies_identity_open hfin)

-- ============================================================
-- Section 5: Connection to twin primes
-- ============================================================

/-- A twin prime pair is (p, p+2) where both are prime -/
def IsTwinPrimePair (p q : ℤ) : Prop :=
  p.natAbs.Prime ∧ q.natAbs.Prime ∧ q = p + 2

/-- Each generator k gives a twin prime pair (6k-1, 6k+1) -/
lemma gen_gives_twin_pair {k : ℤ} (hk : IsTwinPrimeGen k) :
    IsTwinPrimePair (6 * k - 1) (6 * k + 1) :=
  ⟨hk.2.2, hk.2.1, by ring⟩

/-- The map from generators to twin prime pairs is injective -/
lemma gen_to_pair_injective :
    Function.Injective (fun k : ℤ => (6 * k - 1, 6 * k + 1)) := by
  intro a b h
  simp [Prod.ext_iff] at h
  linarith [h.1]

/-- G infinite ↔ infinitely many twin prime pairs -/
theorem twin_primes_iff_G_infinite :
    G.Infinite ↔
    {pair : ℤ × ℤ | IsTwinPrimePair pair.1 pair.2}.Infinite := by
  constructor
  · intro hinf
    apply Set.infinite_of_injective_forall_mem
      (f := fun k : {k : ℤ // IsTwinPrimeGen k} =>
              (6 * k.1 - 1, 6 * k.1 + 1))
    · intro ⟨a, _⟩ ⟨b, _⟩ h
      exact Subtype.ext (gen_to_pair_injective h)
    · intro ⟨k, hk⟩
      exact gen_gives_twin_pair hk
  · intro hinf
    sorry  -- reverse direction: twin prime pairs → generators

-- ============================================================
-- Section 6: Unique factorization
-- ============================================================

/-- φ is injective: φ(a) = φ(b) → a = b -/
lemma φ_injective : Function.Injective φ := by
  intro a b h; simp [φ] at h; linarith

/-- The sign symmetry: -k is a twin-prime generator when k is -/
lemma neg_twin_prime_gen {k : ℤ} (hk : IsTwinPrimeGen k) :
    IsTwinPrimeGen (-k) := by
  refine ⟨by omega, ?_, ?_⟩
  · show (6 * (-k) + 1).natAbs.Prime
    have : (6 * (-k) + 1).natAbs = (6 * k - 1).natAbs := by
      congr 1; ring
    rw [this]; exact hk.2.2
  · show (6 * (-k) - 1).natAbs.Prime
    have : (6 * (-k) - 1).natAbs = (6 * k + 1).natAbs := by
      congr 1; ring
    rw [this]; exact hk.2.1

-- ============================================================
-- Section 7: Summary
-- ============================================================

/-- The full chain:

    TPC (infinitely many twin primes)
      ⟺ |G| = ∞
      ⟺ {(0,0)} is not open in (N, τ_N)
      ⟺ N \ {(0,0)} cannot be covered by finitely many translates a ⊗ N

    The Furstenberg framework gives a clean algebraic reformulation:
    the identity of N cannot be isolated by finitely many cosets.

    Key ingredients:
    1. Irr(N) = G  (generators = irreducibles)
    2. No-zero-component lemma  (injectivity on components)
    3. φ maps to primes  (each |φ(k)| is prime for k ∈ G)
    4. Primality blocks factoring  (prime can't split as ≥5 × ≥5)
-/

end TPC
