-- TPC/Main.lean
-- Main equivalence: TPC ⟺ {1} not open in (N, τ_N)
-- Tensor-irreducibility and the Furstenberg criterion.

import TPC.Basic
import TPC.Monoid
import TPC.Diagonal
import TPC.Topology
import Mathlib.Tactic
import Mathlib.Data.Set.Finite

namespace TPC

-- ============================================================
-- Section 1: Tensor-irreducibility
-- ============================================================

/-- z ⊗ w is tensor-irreducible iff z is ⊛-irreducible and w is ⋆-irreducible.
    A pure tensor MonTensor.mk z w is irreducible if neither z nor w
    can be factored nontrivially in their respective monoids. -/
def IsTensorIrred (t : MonTensor) : Prop :=
  ∃ z w : ℤ, t = MonTensor.mk z w ∧
    (∀ a b : ℤ, a ≠ 0 → b ≠ 0 → mstar a b ≠ z) ∧
    (∀ c d : ℤ, c ≠ 0 → d ≠ 0 → sstar c d ≠ w)

/-- Tensor-irreducible diagonal elements correspond to twin primes:
    diagGen(k) is tensor-irreducible iff 6k+1 and 6k-1 are both prime -/
theorem tensor_irred_iff_twin_prime (k : ℤ) (hk : k ≠ 0) :
    IsTensorIrred (diagGen k) ↔
    (Nat.Prime (6 * k + 1).natAbs ∧ Nat.Prime (6 * k - 1).natAbs) := by
  constructor
  · -- If diagGen(k) = MonTensor.mk k k is tensor-irreducible,
    -- then k is ⊛-irreducible and k is ⋆-irreducible.
    -- ⊛-irreducible k means φ(k) = 6k+1 is ±prime (via φ homomorphism).
    -- ⋆-irreducible k means ψ(k) = 6k-1 is ±prime (via ψ homomorphism).
    intro ⟨z, w, heq, hz_irred, hw_irred⟩
    -- From heq: diagGen k = MonTensor.mk z w, and diagGen k = MonTensor.mk k k
    -- So z = k and w = k (by injectivity of MonTensor.mk, axiomatized)
    sorry
  · -- If 6k+1 and 6k-1 are both prime, then k is both ⊛-irreducible
    -- and ⋆-irreducible, hence diagGen(k) is tensor-irreducible.
    intro ⟨hp, hq⟩
    refine ⟨k, k, rfl, ?_, ?_⟩
    · -- k is ⊛-irreducible: if a ⊛ b = k with a,b ≠ 0 then
      -- φ(a) * φ(b) = φ(k) = 6k+1 which is prime,
      -- but |φ(a)| ≥ 5 and |φ(b)| ≥ 5, product ≥ 25, contradiction.
      intro a b ha hb hab
      have hφ : φ a * φ b = φ k := by rw [← φ_mul, hab]
      have hpa : (φ a).natAbs ≥ 5 := φ_abs_ge_five a ha
      have hpb : (φ b).natAbs ≥ 5 := φ_abs_ge_five b hb
      have habs : (φ a).natAbs * (φ b).natAbs = (φ k).natAbs := by
        rw [← Int.natAbs_mul, hφ]
      -- |φ(k)| = (6k+1).natAbs, which is prime, so ≤ some value
      -- But 5 * 5 = 25 ≤ |φ(a)| * |φ(b)| = |φ(k)|
      -- and |φ(k)| is prime, so |φ(k)| ≥ 25, but a prime p ≥ 25
      -- contradicts being prime only if we know the actual value...
      -- Actually: a prime number cannot equal a product of two numbers each ≥ 5
      -- because if n = a * b with a ≥ 5 and b ≥ 5, then n ≥ 25 and n is composite.
      -- But we need: a prime p with p = a * b forces a = 1 or b = 1.
      -- Since a ≥ 5 and b ≥ 5, neither is 1, so p is not prime. Contradiction.
      sorry
    · -- k is ⋆-irreducible: symmetric argument with ψ
      intro c d hc hd hcd
      sorry

-- ============================================================
-- Section 2: General Furstenberg Criterion
-- ============================================================

/-- General Furstenberg Criterion for generated monoids.

    Let (N, ·, 1) be a commutative monoid generated by a set Irr.
    Equip N with the coarsest topology making every translate a·N closed.
    Then:
      |Irr| = ∞  ⟺  {1} is not open

    Direction (⇐): Irr finite → N\{1} = ⋃_{q∈Irr} q·N = finite union
                    of closed sets = closed → {1} open.
    Direction (⇒): Any finite covering N\{1} = ⋃ aᵢ·N forces every
                    irreducible to be one of the aᵢ → |Irr| ≤ k. -/

-- ============================================================
-- Section 3: (⇐) direction — G finite implies {1} open
-- ============================================================

/-- If G is finite, then {1} is open in (MonTensor, τ) -/
theorem G_finite_implies_identity_open (hfin : G.Finite) :
    IsOpen ({1} : Set MonTensor) := by
  -- N \ {1} = ⋃_{g ∈ G} translateN g (by H1)
  -- This is a finite union of closed sets, hence closed.
  -- So {1} is open.
  sorry

-- ============================================================
-- Section 4: (⇒) direction — G infinite implies {1} not open
-- ============================================================

/-- If G is infinite, then {1} is not open in (MonTensor, τ) -/
theorem G_infinite_implies_identity_not_open (hinf : G.Infinite) :
    ¬ IsOpen ({1} : Set MonTensor) := by
  -- If {1} were open, then N \ {1} would be closed,
  -- hence a finite union of translates aᵢ · N.
  -- By generator_in_translate_forces_eq, every g ∈ G is one of the aᵢ.
  -- So |G| ≤ k, contradicting G.Infinite.
  sorry

-- ============================================================
-- Section 5: The equivalence
-- ============================================================

/-- TPC ⟺ {1} not open:
    |G| = ∞  ⟺  {1} is not open in (N, τ_N) -/
theorem TPC_equivalence :
    G.Infinite ↔ ¬ IsOpen ({1} : Set MonTensor) := by
  constructor
  · exact G_infinite_implies_identity_not_open
  · intro h
    by_contra hfin
    rw [Set.not_infinite] at hfin
    exact h (G_finite_implies_identity_open hfin)

-- ============================================================
-- Section 6: Connection to twin primes
-- ============================================================

/-- A twin prime pair is (p, p+2) where both are prime -/
def IsTwinPrimePair (p q : ℤ) : Prop :=
  p.natAbs.Prime ∧ q.natAbs.Prime ∧ q = p + 2

/-- Each generator k gives a twin prime pair (6k-1, 6k+1) -/
lemma gen_gives_twin_pair {k : ℤ} (hk : IsTwinPrimeGen k) :
    IsTwinPrimePair (6 * k - 1) (6 * k + 1) :=
  ⟨hk.2.2, hk.2.1, by ring⟩

/-- The map from generators to twin prime pairs is injective -/
lemma gen_to_pair_injective :
    Function.Injective (fun k : ℤ => (6 * k - 1, 6 * k + 1)) := by
  intro a b h
  simp [Prod.ext_iff] at h
  linarith [h.1]

/-- G infinite ↔ infinitely many twin prime pairs -/
theorem twin_primes_iff_G_infinite :
    G.Infinite ↔
    {pair : ℤ × ℤ | IsTwinPrimePair pair.1 pair.2}.Infinite := by
  constructor
  · intro hinf
    apply Set.infinite_of_injective_forall_mem
      (f := fun k : {k : ℤ // IsTwinPrimeGen k} =>
              (6 * k.1 - 1, 6 * k.1 + 1))
    · intro ⟨a, _⟩ ⟨b, _⟩ h
      exact Subtype.ext (gen_to_pair_injective h)
    · intro ⟨k, hk⟩
      exact gen_gives_twin_pair hk
  · intro hinf
    sorry  -- reverse direction: twin prime pairs → generators

-- ============================================================
-- Section 7: The sign symmetry
-- ============================================================

/-- The sign symmetry: -k is a twin-prime generator when k is -/
lemma neg_twin_prime_gen {k : ℤ} (hk : IsTwinPrimeGen k) :
    IsTwinPrimeGen (-k) := by
  refine ⟨by omega, ?_, ?_⟩
  · show (6 * (-k) + 1).natAbs.Prime
    have : (6 * (-k) + 1).natAbs = (6 * k - 1).natAbs := by
      congr 1; ring
    rw [this]; exact hk.2.2
  · show (6 * (-k) - 1).natAbs.Prime
    have : (6 * (-k) - 1).natAbs = (6 * k + 1).natAbs := by
      congr 1; ring
    rw [this]; exact hk.2.1

-- ============================================================
-- Section 8: Summary
-- ============================================================

/-- The full chain (tensor product formulation):

    TPC (infinitely many twin primes)
      ⟺ |G| = ∞   where G = {diagGen(k) : k is a twin-prime index}
      ⟺ {1} is not open in (N, τ_N)
      ⟺ N \ {1} cannot be covered by finitely many translates a · N

    N = ⟨{k ⊗ k : k ∈ ℤ}⟩ ⊆ MonTensor = (ℤ, ⊛) ⊗_Mon (ℤ, ⋆)

    Key ingredients:
    1. Irr(N) = G  (generators = irreducibles, via tensor-irreducibility)
    2. Bilinearity of the tensor product
       (a ⊛ b) ⊗ w = (a ⊗ w) · (b ⊗ w)
       z ⊗ (c ⋆ d) = (z ⊗ c) · (z ⊗ d)
    3. φ maps to primes  (each |φ(k)| is prime for k ∈ G)
    4. ψ maps to primes  (each |ψ(k)| is prime for k ∈ G)
    5. Primality blocks factoring  (prime can't split as ≥5 × ≥5)
    6. The UMP topology from β : ℤ × ℤ → MonTensor
-/

end TPC
